apiVersion: v1
kind: ConfigMap
metadata:
  name: gdd-stress-env
data:
  CATALOG_URL: 'jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=90)(RETRY_COUNT=30)(RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.1.19)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=GDS$CATALOG.raft_vmdb)))'
  GDS_UUID_URL: 'jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=90)(RETRY_COUNT=30)(RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.1.19)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=sub_u_rw_svc.bnh.raft_vmdb)))'
  GDS_SEQ_URL: 'jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=90)(RETRY_COUNT=30)(RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.1.19)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=sub_s_rw_svc.bnh.raft_vmdb)))'
---
apiVersion: v1
kind: Secret
metadata:
  name: gdd-stress-secret
type: Opaque
stringData:
  GDD_USERNAME: "SOE"
  GDD_PASSWORD: "Support#BNH#123"
